import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { ThemeProvider } from "@/components/providers/ThemeProvider";
import { cn } from "@/lib/utils";
import { ModalProvider } from "@/components/providers/ModalProvider";
import { currentUser } from "@clerk/nextjs/server";
import { db } from "@/lib/db";
import { SocketProvider } from "@/components/providers/SocketProvider";

const font = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // to synchronize clerk user info with the corresponding db profile entity.
  // workaround to avoid using clerk user update webhooks.
  const user = await currentUser();

  if (user) {
    console.log("Syncing profile info and user info...");
    await db.profile.update({
      where: {
        userId: user.id,
      },
      data: {
        name: user.fullName || "Guest",
        imageUrl: user.imageUrl,
      },
    });
  }

  return (
    <ClerkProvider afterSignOutUrl="/">
      <html lang="en" suppressHydrationWarning>
        <body className={cn(font.className, "bg-white dark:bg-[#313338]")}>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem={false}
            storageKey="discord-theme"
          >
            <SocketProvider>
              <ModalProvider />
              {children}
            </SocketProvider>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
